on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: "macos-latest"
            args: "--target aarch64-apple-darwin"
          - os: "macos-latest"
            args: "--target x86_64-apple-darwin"
          - os: "ubuntu-latest"
            args: ""
          - os: "windows-latest"
            args: ""

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - uses: dtolnay/rust-toolchain@stable

      - if: matrix.os == 'ubuntu-latest' # Linux only
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - if: matrix.os == 'ubuntu-latest' # Linux only
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - id: cargo-cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-registry-

      - run: npm ci

      - uses: tauri-apps/tauri-action@v0
        with:
          tagName: v__VERSION__
          releaseName: "Release v__VERSION__"
          releaseDraft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
